{"name": "test_login_lostsec", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <allure_practice.test_feature_story.TestLogin object at 0x0000025503065880>\n\n    @allure.story('密码缺失')\n    def test_login_lostsec(self):\n    \n        # 对一些关键步骤进行标记\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:39: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1617534848102, "stop": 1617534848102}, {"name": "点击密码", "status": "passed", "start": 1617534848102, "stop": 1617534848102}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\Programs\\DevOps\\Python_Practice\\allure_practice\\test_feature_story.py\", line 39, in test_login_lostsec\n    assert \"1\" == 1\n"}, "start": 1617534848102, "stop": 1617534848102}], "attachments": [{"name": "stdout", "source": "68a23772-310e-482d-8815-ecc1b42d1acc-attachment.txt", "type": "text/plain"}], "start": 1617534848101, "stop": 1617534848103, "uuid": "4a9040a9-04f6-4549-9a0c-4cedf49170dc", "historyId": "b7fdb56c23e32c9a4d4410bd5cefdb11", "testCaseId": "60412d4434c16d0e34a4addbfc65ce03", "fullName": "test_feature_story.TestLogin#test_login_lostsec", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-UL20B91J"}, {"name": "thread", "value": "14780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}