{"name": "test_login_lostsec", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1", "trace": "self = <allure_practice.test_feature_story.TestLogin object at 0x000001F61D88F700>\n\n    @pytest.mark.run(order=-1)\n    @allure.story('密码缺失')\n    def test_login_lostsec(self):\n    \n        # 对一些关键步骤进行标记\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\nE             +'1'\nE             -1\n\ntest_feature_story.py:42: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1617852874961, "stop": 1617852874961}, {"name": "点击密码", "status": "passed", "start": 1617852874961, "stop": 1617852874961}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n  +'1'\n  -1\n", "trace": "  File \"D:\\Python Project\\Python_Practice\\allure_practice\\test_feature_story.py\", line 42, in test_login_lostsec\n    assert \"1\" == 1\n"}, "start": 1617852874961, "stop": 1617852874961}], "start": 1617852874961, "stop": 1617852874962, "uuid": "7143cafb-c393-48db-940b-25cba3caba62", "historyId": "b7fdb56c23e32c9a4d4410bd5cefdb11", "testCaseId": "60412d4434c16d0e34a4addbfc65ce03", "fullName": "test_feature_story.TestLogin#test_login_lostsec", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "tag", "value": "run(order=-1)"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "zhangtao"}, {"name": "thread", "value": "10524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}